### ISSUE TITLE
Use a more inforative error message

### ISSUE THREAD

**Issue by beboche** [openvar/variantValidator#437] opened 2022-10-28 08:11 UTC
A MobiDetails user keeps submitting this kind of variant:

NM_000516.7:c.2780+73C>T
NM_000516.7:c.1682+73C>T
...
For this transcript, the stop codon ends at position c.1185, according to Mutalyzer. Then the submitted nomenclature is totally wrong, we agree on that.

However, the VV [answer](https://rest.variantvalidator.org/VariantValidator/variantvalidator/GRCh38/NM_000516.7:c.1682+73C%3ET/all?content-type=application/json) is: 

> ['Required information for NM_000516.7 is missing from the Universal Transcript Archive', 'Query gene2transcripts with search term NM_000516 for available transcripts']

which is not really informative (note: VV is able to correctly validate [other variants](https://rest.variantvalidator.org/VariantValidator/variantvalidator/GRCh38/NM_000516.7:c.2del/all?content-type=application/json) on this transcript).

Something like 

> position c.2780 is not an exon/intron boundary

 or

> position c.2780 is located after the stop codon

would make more sense to me.

Alternatively, or even primarily, VV coul just validate the variant, changing e.g. NM_000516.7:c.1682+73A>T into NM_000516.7:c.*570A>T

Thanks for considering it

**Comment by Peter-J-Freeman** [comment] 2022-10-28 13:01
Looks like this is being picked up by code that was intended to catch a different type of bug. 

The transcript is indeed available in our database.

VV does usually handle miss-placing of the cds end https://github.com/openvar/variantValidator/issues/432 which may still need pushing up, but I need to check why this particular warning is being generated.

What I can say is that if the stop codon ends at c.1185, NM_000516.7:c.1682+73C>T it would not be obvious to me to convert into NM_000516.7:c.*570A>T because I am not sure whether the user is intending to describe a variant in a 3 prime UTR intron or whether they think the stop codon ends at 1682. There ought to be an error message, but what should it be. Asking @leicray @ifokkema @jtdendunnen for help with this one please

**Comment by Peter-J-Freeman** [comment] 2022-10-28 13:23
The error message is currently a bit of a red-herring because it is intended to identify transcripts not in the database, but in this instance, other data needed to handle this malformed variant are not available. The gene is GNAS. There are no introns in the 3 prime UTR. The 3 prime UTS seem to be 364 bases in length. 1185+364=1549. So c. 2780 and c. 1682 are beyond the boundaries of the transcript??? I cannot fathom what the user is trying to accomplish with c.1682 or c.2780. 

https://www.ncbi.nlm.nih.gov/nuccore/1859766330

**Comment by beboche** [comment] 2022-10-28 13:27
> I cannot fathom what the user is trying to accomplish with c.1682 or c.2780.

yes no idea too. He/she tried 2-3 variants of the same type on this transcript, then came back to do the same the day after.

**Comment by Peter-J-Freeman** [comment] 2022-10-28 13:43
@beboche .Glad it's not just me

**Comment by ifokkema** [comment] 2022-10-31 11:22
I would honestly stick to an error informing the user there's no exon ending at c.2780 or c.1682. I wouldn't start doing any math with the given intronic offset to try and figure out what the user meant. In case they then try c.2780 without an intronic offset, one could change that into a UTR position by subtracting the CDS length (including the stop codon), but I wouldn't recommend that to be a silent correction, more like a suggestion included in an error message like "The CDS of NM_000516.7 is only ... bases long. Perhaps you meant c.*....?".

**Comment by leicray** [comment] 2022-10-31 11:46
I agree with @ifokkema suggesting that the error message be kept as simple as possible. The CDS for NM_000516.7 is 1185 nucleotides. Hence, c.2780 are c.1682 are not valid positions irrespective of considerations of exon end points.

This highlight the need to (perhaps) have separate error messages for situations such as this (attempts to validate variants relative to positions outside the CDS) and for variant descriptions that are supposedly intronic but for which the intronic offset is not described relative to a true exon start or end location.

**Comment by Peter-J-Freeman** [comment] 2022-10-31 12:09
That would also be my preference. @beboche , that OK with you?

**Comment by Peter-J-Freeman** [comment] 2022-11-02 12:03
Brilliant. Will tackle this ADSAP

**Comment by Peter-J-Freeman** [comment] 2022-11-02 16:46
OK, the original warning there was being thrown because the description went beyind the transcript bounday in a weird unexpected way. So I propose the following warning

        "validation_warnings": [
            "Variant start position and/or end position are beyond the CDS end and possibly the end of the selected reference sequence"
        ],

**Comment by ifokkema** [comment] 2022-11-03 11:01
Good to be strict. You could add the info that positions beyond the CDS but within the transcript can be numbered with an asterisk, but this may complicate a compact and perfectly sensible warning message.

If a position within the CDS is given with an intronic offset there where there is no exon end, will that now or soon also generate a warning/error?

**Comment by Peter-J-Freeman** [comment] 2022-11-03 11:06
I think we can expand the warning easily if there is need to. Thanks for the confirmation that is is good.

> If a position within the CDS is given with an intronic offset there where there is no exon end, will that now or soon also generate a warning/error?

As I understand it, if the coordinates are within the transcript (CDS or UTRs) and the exon boundary position is given incorrectly, then VV warns and corrects. The issue here is that a "Data not available error" was being thrown because the tool was trying to map beyond the boundary of the reference sequence and did not know what to do with itself

**Comment by ifokkema** [comment] 2022-11-03 11:56
> > If a position within the CDS is given with an intronic offset there where there is no exon end, will that now or soon also generate a warning/error?
> 
> As I understand it, if the coordinates are within the transcript (CDS or UTRs) and the exon boundary position is given incorrectly, then VV warns and corrects.

I disagree this is a correction; I believe the chance that c.100+5 is meant to be c.105 is nearly zero. I'm afraid that perhaps users don't pick up the warning properly because VV produces output. LOVD's VV library catches these rare cases and disregards VV's suggestion, throwing an error instead.

Like @leicray mentioned:
> This highlights the need to (perhaps) have separate error messages for situations such as this (...) and for variant descriptions that are supposedly intronic but for which the intronic offset is not described relative to a true exon start or end location.

I agree with @leicray that an error message would be better than a "correction".

**Comment by Peter-J-Freeman** [comment] 2022-11-03 12:13
Can you give some examples of variants and some suggested error messages? Makes it easier if I know exactly what is wanted

**Comment by leicray** [comment] 2022-11-07 12:00
Validating the variant description `NM_000518.5:c.89+25del` generates the error message `The entered coordinates do not agree with the intron/exon boundaries for the selected transcript` which is correct, but not sufficiently informative. A clearer error message would be `c.89 does not lie at an exon boundary`. In addition, VV should not attempt to correct the description to `NM_000518.5:c.92+22del` as that might not reflect what was intended.

The variant description `NM_000518.5:c.92+80del` is appropriately corrected to `NM_000518.5:c.93-51del` but the error message that is displayed is also `The entered coordinates do not agree with the intron/exon boundaries for the selected transcript`. This is misleading as c.92 does lie at an exon boundary. The problem in this instance is that intron position +80 is invalid as that position would lie beyond the centre point of the intron. A clearer error message would be `The intron position is invalid`.

**Comment by Peter-J-Freeman** [comment] 2022-11-08 09:07
For ease, I'm going to open this as a new issue. Can we all confirm that we are happy with the error message relating to this bug? @ifokkema @beboche @leicray. I can then close this issue and fix the new issue separately

**Comment by beboche** [comment] 2022-11-08 09:12
I am happy

**Comment by leicray** [comment] 2022-11-08 09:17
I am happy

**Comment by ifokkema** [comment] 2022-11-08 09:17
Yes, the "(...) beyond the CDS (...)" message for this issue, is great!

**Comment by Peter-J-Freeman** [comment] 2022-11-08 09:26
Fantastic. I will close this then.

**Closed** 2022-11-09 09:42 UTC
