### ISSUE TITLE
Inconsistent query output

### ISSUE THREAD

**Issue by holtgrewe** [openvar/variantValidator#544] opened 2023-09-05 07:03 UTC
**Describe the bug**
Certain query return warnings stochastically.

**To Reproduce**
1. Go to `https://rest.variantvalidator.org/VariantValidator/variantvalidator/GRCh37/17-41197751-G-T/all?content-type=application%2Fjson`
2. Reload a couple of times
3. See warnings and successful results some times

**Expected behavior**
The results should be consistent.

**Comment by ifokkema** [comment] 2023-09-07 08:12
Sounds like a possible duplicate of #421.

**Comment by Peter-J-Freeman** [comment] 2024-04-17 13:13
We hae added a new method to the API to resolve this. Will be made more powerful in a couple of weeks too. We beefed up the servers to handle additional traffic.

**Closed by Peter-J-Freeman** 2024-04-17 13:13 UTC
