### ISSUE TITLE
Timeout when processing NC_000001.10:g.76205798A>G

### ISSUE THREAD

**Issue by loeswerkman** [openvar/variantValidator#344] opened 2022-02-04 12:03 UTC
When mapping the variant NC_000001.10:g.76205798A>G using 'primary' as the liftover setting and mapping on 'all' transcripts, [this](https://rest.variantvalidator.org/LOVD/lovd/hg19/NC_000001.10%3Ag.76205798A%3EG/refseq/all/tx/primary?content-type=application%2Fjson) takes 30+ seconds and results in a timeout error.
When we add 'NM_000016.4' as the only transcript, [this](https://rest.variantvalidator.org/LOVD/lovd/hg19/NC_000001.10%3Ag.76205798A%3EG/refseq/NM_000016.4/tx/primary?content-type=application%2Fjson) takes 10 seconds, while when we turn off the liftover completely and use 'False' instead of 'primary', [this](https://rest.variantvalidator.org/LOVD/lovd/hg19/NC_000001.10%3Ag.76205798A%3EG/refseq/NM_000016.4/tx/False?content-type=application%2Fjson) takes only 0.1 second.

Could the liftover be sped up somehow? Should it take 10 seconds for one variant on one transcript? Or is VV perhaps mapping four times for all four genome builds when using 'primary'? While, of course, VV only really needs to map twice, since hg19==GRCh37 for all chromosomes other than 'M', and hg38==GRCh38.

**Comment by i3hsInnovation** [comment] 2022-02-04 12:56
You have already worked out how to speed things up. It is essential that vv considers each transcript separately because you cannot be certain every transcript for a gene has the same exon structure, or even sequence, and so outputs must be calculated accurately. Also, for genes with many transcripts, this takes longer.

You could simply set select_transcripts to select which will limit to the canonical transcript for each gene. mane can be used for genes with Mane select transcripts. Otherwise set to liftover only.

**Comment by i3hsInnovation** [comment] 2022-02-04 12:58
Going to close this because the methods are in place. I'm planning some profiling to speed up vv in general, but it's low priority until I get staff. Unless you fancy a go? 🤣. I know a way to really speed things up but don't have time to commit! 😛

**Comment by ifokkema** [comment] 2022-02-04 13:23
We agree that liftover needs to be done per transcript, so in that sense, it was expected that selecting the transcript sped things up (that's why we tried). If you:
- Think 10 seconds liftover per variant per transcript is normal/expected;
- Can confirm that liftover is done to hg19/GRCh37 *once* and to hg38/GRCh38 *once*, so two operations in total instead of four;

then the issue can be closed 😅

> (...) until I get staff. Unless you fancy a go? rofl. I know a way to really speed things up but don't have time to commit! :stuck_out_tongue:

Haha I'll leave this for Loes to reply to, I'm too busy already 😂

**Comment by i3hsInnovation** [comment] 2022-02-04 14:34
Come on Ivo. You know that normal logic can't be applied to computers! They do what they want! 😂. 

I guess that, For example, people could have been running transcript based queries regularly on a gene, so the most regularly used transcripts are cached. But then you do a genomic query, it takes longer to get the uncached data. John is looking at models to speed this stuff up with differential indexing etc, but again finding needed.

I'd personally just set select transcripts to refseq.

Ill look forward to Loes reply! 😂

**Comment by ifokkema** [comment] 2022-02-04 15:18
> Come on Ivo. You know that normal logic can't be applied to computers! They do what they want! :joy:.

:joy:
Right... I should have known :laughing: 

Buuuuut.... I've been thinking about this some more. And something is definitely wrong. Please check my reasoning;
1. g. => c. without liftover is instant. This involves;
  a. validating the g. input
  b. mapping g. to c.
  c. validating c.
2. when adding liftover, this adds:
  a. mapping c. to g. (x2) (reverse of 1b, but twice)
  b. validating generated g. (x2) (same as 1a, but twice)

"Logic" would tell me that the execution time of process 2 would never be more than 5x the execution time of process 1. However, it's 100x the execution time. I also remember that I've dealt with variants mapping to ~5 transcripts or more, with liftover, and now we can't even really do variants with two transcripts. If the argument would be that c. to g. would be much more challenging, then VV should be slow as well. Finally, it's not a matter of caching because repeating the same request does not speed up execution. OK, so I tested everything. The error is somewhere in the transcript as well as the endpoint.

| Variant | Transcript | Excecution time LOVD | Execution time VV |
|--|--|--|--|
| NC_000001.10:g.76205798A>G | NM_000016.4 | 10 sec | 10 sec |
| NC_000001.10:g.76205798A>G | NM_000016.5 | 10 sec | <1 sec |
| NC_000001.10:g.76205798A>G | NM_000016.6 | 10 sec | <1 sec |
| NC_000001.10:g.76205795G>A | NM_000016.4 | 10 sec | 12 sec |
| NC_000001.10:g.76205795G>A | NM_000016.5 | 10 sec | 2 sec |
| NC_000001.10:g.76205795G>A | NM_000016.6 | 10 sec | 2 sec |

Note, NC_000001.10:g.76205798A>G is located in the intron, NC_000001.10:g.76205795G>A is located in the exon.

As the LOVD endpoint was designed to be faster than VV by disabling features, it should really match VV's speed, *or* be faster. Currently, for these transcripts, it's slower.

Does this help track down what's going on?

**Comment by i3hsInnovation** [comment] 2022-02-04 15:41
Oh, it might actually. I have a vague memory that I made VV save the lifted over first genomic position it creates as this will be static. I wonder if VF (and Lovd) are unnecessarily still doing multiple liftover.

Ok, you can keep the issue open. I'll look at it next week.

Still waiting for Loes response! 😜

**Comment by ifokkema** [comment] 2022-02-04 16:58
> Oh, it might actually. I have a vague memory that I made VV save the lifted over first genomic position it creates as this will be static. I wonder if VF (and Lovd) are unnecessarily still doing multiple leftover.

Could this be slower by a factor of 100? 🤔 The differences between NM_000016.4 and NM_000016.5 when both using VV suggest that there's something in the transcripts that trouble the mapping as well. Well, anyway, I hope you can find it 😅


> Still waiting for Loes response! :stuck_out_tongue_winking_eye:

Haha, I'd like to keep her for a while still, but I don't have anything to say about what she does on the weekends... 😁

**Comment by PeteCausey-Freeman** [comment] 2022-02-07 15:47
I'm just thinking that the only way I can really figure out what's going on is to run some serious profiling. See where variants go through the code, and whether there is a code bottleneck. I don't think my previous suggestion of caching was correct for VF. The question I addressed for VV was for a different purpose. It would not speed up VF in the same way.

I can't promise when I'll get the time to look at this because it's not the highest priority, but I want to do some more stuff around profiling in the educational setting. Perhaps I'll take time out to develop educational material and use your examples as a case study.

**Comment by PeteCausey-Freeman** [comment] 2022-05-24 08:48
@ifokkema and @loeswerkman . Has the new server config solved this"?

**Comment by PeteCausey-Freeman** [comment] 2022-05-26 09:47
Closing this issue because the new server config seems to be adding major benefits

**Closed by PeteCausey-Freeman** 2022-05-26 09:47 UTC
