### ISSUE TITLE
local installation issues

### ISSUE THREAD

**Issue by AnotherSimon** [openvar/variantValidator#149] opened 2020-04-15 09:21 UTC
Dear package maintainers,

After following the install guide at "https://github.com/openvar/variantValidator/blob/master/docs/INSTALLATION.md" (with conda option), I am unable to generate the config file automatically:

`
(vvenv) sdenil@testsrv:~/software/variantValidator$ vv_configure.py 
Traceback (most recent call last):
  File "/home/sdenil/software/anaconda3/envs/vvenv/bin/vv_configure.py", line 4, in <module>
    __import__('pkg_resources').run_script('VariantValidator==1.0.4.dev17+gd16b9ef', 'vv_configure.py')
  File "/home/sdenil/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/sdenil/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1471, in run_script
    exec(script_code, namespace, namespace)
  File "/home/sdenil/software/anaconda3/envs/vvenv/lib/python3.6/site-packages/VariantValidator-1.0.4.dev17+gd16b9ef-py3.6.egg/EGG-INFO/scripts/vv_configure.py", line 31, in <module>
  File "/home/sdenil/software/anaconda3/envs/vvenv/lib/python3.6/site-packages/VariantValidator-1.0.4.dev17+gd16b9ef-py3.6.egg/EGG-INFO/scripts/vv_configure.py", line 16, in read_settings
  File "/home/sdenil/software/anaconda3/envs/vvenv/lib/python3.6/site-packages/VariantValidator-1.0.4.dev17+gd16b9ef-py3.6.egg/EGG-INFO/scripts/vv_configure.py", line 11, in find_root
TypeError: zipimporter.get_filename() takes exactly 1 argument (0 given)
`

As a workaround I have created a config file manually at "~/.variantvalidator/default.ini". This does not seem effective however as I get the following result for trying to run variant_validator.py:

`
(vvenv) sdenil@testsrv:~/software/variantValidator$ variant_validator.py -h
Traceback (most recent call last):
  File "/home/sdenil/software/anaconda3/envs/vvenv/bin/variant_validator.py", line 4, in <module>
    __import__('pkg_resources').run_script('VariantValidator==1.0.4.dev17+gd16b9ef', 'variant_validator.py')
  File "/home/sdenil/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/sdenil/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1471, in run_script
    exec(script_code, namespace, namespace)
  File "/home/sdenil/software/anaconda3/envs/vvenv/lib/python3.6/site-packages/VariantValidator-1.0.4.dev17+gd16b9ef-py3.6.egg/EGG-INFO/scripts/variant_validator.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/sdenil/software/anaconda3/envs/vvenv/lib/python3.6/site-packages/VariantValidator-1.0.4.dev17+gd16b9ef-py3.6.egg/VariantValidator/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/sdenil/software/anaconda3/envs/vvenv/lib/python3.6/site-packages/VariantValidator-1.0.4.dev17+gd16b9ef-py3.6.egg/VariantValidator/configure.py", line 31, in <module>
  File "/home/sdenil/software/anaconda3/envs/vvenv/lib/python3.6/site-packages/VariantValidator-1.0.4.dev17+gd16b9ef-py3.6.egg/VariantValidator/configure.py", line 11, in read_configuration
  File "/home/sdenil/software/anaconda3/envs/vvenv/lib/python3.6/site-packages/backports/configparser/__init__.py", line 1040, in __getitem__
    raise KeyError(key)
KeyError: 'mysql'
`

Clearly something is still going wrong with option parsing.

PS: `update_vdb.py` suffers form the same problem.
PPS: I'm working with the MySQL db dump (this required `ALL PRIVILEGES` to work rather than just `SELECT,INSERT,UPDATE,DELETE` as stated in the manual).

**Comment by PeteCausey-Freeman** [comment] 2020-04-15 09:31
Hi @AnotherSimon .

Before continuing, I will just let you know that the code is undergoing some re-development to fix some bugs and add new functionality. I recommend re-cloning from the https://github.com/openvar/variantValidator/tree/features branch which will be incorporated into master in the next couple of weeks.

Any updates to installation are here.

https://github.com/openvar/variantValidator/blob/features/docs/INSTALLATION.md

So let's work this through. These instructions have worked for me but perhaps we can improve them together?

Please could you re-clone from the correct branch and log your steps. Also provide any information. Thanks in advance for your help.

Alternatively, depending on what you want to use the tool for, we have a REST API which can be accessed through our web services or can be installed through Docker. This is probably the most convenient way to locally install our tools.

Happy to help and discuss the options

**Comment by AnotherSimon** [comment] 2020-04-15 09:54
Hi Pete,

API won't be an option because the variants are derived from human patient data and the policy is to analyse locally where possible (even though the case for identification is arguably small here).

Happy to look into the docker option if it runs fully locally. (didn't spot any instructions for the docker)

I'll have a new go at it with the branch you recommended and compile a log of commands and outputs in case I run into anything.

**Comment by PeteCausey-Freeman** [comment] 2020-04-15 09:59
No probs.

My recommendation is this then.

Clone rest_variantValidator from the requests branch. Again, huge active development ongoing. We are now supporting the LOVD project and I'm working with Ivo at LOVD to improve our outputs and provide new API endpoints.

https://github.com/openvar/rest_variantValidator/tree/requests

The docker installation can be found here
https://github.com/openvar/rest_variantValidator/blob/requests/docs/DOCKER.md

My advice is be patient and run the instructions to the letter. Let me know if anything goes wrong. There have been issues, but it's the most convenient way to install and access the tools.

Effectively all you need once you have installed is something like the Python requests module to hit a locally installed version of the API. Simples!

**Comment by ifokkema** [comment] 2020-04-16 07:45
If I may ask, @AnotherSimon , could you keep us updated here about your progress? I tried setting up VV using Docker before but got too many errors for me to fix (I'm a novice at Docker). In case you manage, your steps would be very useful for me!

**Comment by PeteCausey-Freeman** [comment] 2020-04-16 10:39
Agreed. Hopefully between us we can create some robust installation guides. Would really appreciate feedback from you guys

**Comment by AnotherSimon** [comment] 2020-04-16 13:06
First try with docker container (REST version) went smoothly until I hit the following snag:

`
ERROR: for uta  Cannot start service uta: driver failed programming external connectivity on endpoint rest_variantvalidator_uta_1 (b6879ddb9d4c10de78ce05eab61c2c8325d69924b727766428a2f7bbcd7a44cc): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use
ERROR: for vdb  Cannot start service vdb: driver failed programming external connectivity on endpoint rest_variantvalidator_vdb_1 (ee7165b8be935a85bc61f2a3f6e847defa0db8afb39654e438a6e2cda64483cf): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use
`

The shared server I am working on already has mysql and postgres installed on it for other applications. By default the docker container is configured to use the ports 3308 and 5432 respectively but this should be a configurable option before executing `docker-compose build --no-cache`, perhaps as an additional option in `docker.ini`.

**Comment by PeteCausey-Freeman** [comment] 2020-04-16 13:20
Here is the docker-compose-yml
https://github.com/openvar/rest_variantValidator/blob/master/docker-compose.yml

```yml
version: '3'

services:
  vdb:
    build:
      context: .
      dockerfile: vdb_docker.df
    ports:
      - "3306:3306"
    expose:
      - "3306"
  uta:
    build:
      context: .
      dockerfile: uta_docker.df
    ports:
      - "5432:5432"
    expose:
      - "5432"
  seqrepo:
    image: biocommons/seqrepo:2018-08-21
    volumes:
      - seqdata:/usr/local/share/seqrepo
    stdin_open: true
    tty: true
  restvv:
    build: .
    depends_on:
      - vdb
      - uta
    volumes:
      - seqdata:/usr/local/share/seqrepo
    ports:
      - "5000:5000"
      - "8000:8000"
      - "8080:8080"

volumes:
  seqdata:
```

**Comment by PeteCausey-Freeman** [comment] 2020-04-16 13:22
In theory the ports should be changeable. @ifokkema , are there any common alternate ports for these that @AnotherSimon can try.

**Comment by ifokkema** [comment] 2020-04-16 14:13
I remember having the same issue - just MySQL in my case. I tried changing the ports, but I couldn't get it to work (the cause could be me). Anything above 1024 is fair game, I think I tried to change it to 33060 or so.

**Comment by AnotherSimon** [comment] 2020-04-16 14:13
Ok,  so apparently changing the ports does not brake the docker container so it's safe to edit those in the yml file, I chose `33306:3306` and `55432:5432` for ease of use.

I can now use the service with ssh -X, opening a browser and going to the address provided in the install guide. Next step, make API calls from python on the host machine.

PS: For my application I will need to convert VCF variants to HGVS format (first genomic and then maybe in transcript coordinates later). The manual mentions that this functionality only exists for GRCh38. Mildly annoying for me but there are tools like liftover that work just fine. Consider it a feature request, should only be a matter of adding in a flag and a second dictionary to lookup the relevant IDs.
What could be mildly confusing though, is that the formatter module will let you try none the less (see screenshot attached). Perhaps conditional drop-down options would be appropriate? Or perhaps a warning in the text field listing the examples since many users will not (fully) read the manual.
![Screenshot from 2020-04-16 16-04-11](https://user-images.githubusercontent.com/36060453/79466015-50110400-7ffc-11ea-8e4d-0bd557265c4b.png)

**Comment by PeteCausey-Freeman** [comment] 2020-04-16 14:15
Not sure where you got that from. Works for GRCh37 too :). For VCF you MUST specify the genome build

**Comment by AnotherSimon** [comment] 2020-04-16 14:18
from the output:
{
  "17-50198002-C-A": {
    "errors": [],
    "17-50198002-C-A": {
      "p_vcf": null,
      "g_hgvs": null,
      "genomic_variant_error": "NC_000017.10:g.50198002C>A: Variant reference (C) does not agree with reference sequence (G)",
      "hgvs_t_and_p": null
    }
  },
  "metadata": {
    "variantvalidator_version": "1.0.4.dev17+gd16b9ef",
    "variantvalidator_hgvs_version": "1.2.5.vv1",
    "uta_schema": "uta_20180821",
    "seqrepo_db": "/usr/local/share/seqrepo/2018-08-21"
  }
}

**Comment by PeteCausey-Freeman** [comment] 2020-04-16 14:20
Did you by any chance submit the same variant description to GRCh37 and GRCh38. You cannot so this. The mapped positions will not be the same. This error message is correct. The reference sequences are entirely different.

**Comment by PeteCausey-Freeman** [comment] 2020-04-16 14:21
Ha. Nice one :)
It's OK you wont be the last!

**Comment by PeteCausey-Freeman** [comment] 2020-04-16 14:22
Use the VariantValidator endpoint. It will attempt to auto lift between the different builds for you

**Comment by ifokkema** [comment] 2020-04-16 14:22
Nice that you got it to work! There's hope for me, then! :sweat_smile: 

Note, `select_transcripts` should be set to "None" in your case. "multiple transcript ids" is part of the documentation, but not a valid option.

**Comment by AnotherSimon** [comment] 2020-04-16 14:23
With respect to where I got the idea that it was GRCh38  only: 
https://github.com/openvar/variantValidator/blob/features/docs/MANUAL.md

Ctrl+F for "# GRCh38 only"

**Comment by PeteCausey-Freeman** [comment] 2020-04-16 14:24
I would also recommend re-installing from branch 
https://github.com/openvar/rest_variantValidator/tree/requests
The screen shot is from a very old version which still lives in master.

**Comment by PeteCausey-Freeman** [comment] 2020-04-16 14:24
I would also recommend re-installing from branch 
https://github.com/openvar/rest_variantValidator/tree/requests
The screen shot is from a very old version which still lives in master. 

Agreed to the manual though. I will update the text

**Comment by PeteCausey-Freeman** [comment] 2020-04-16 14:25
I will also update the docker manual specifying that the ports can be changed. 

Would this be ok for both of you guys?

**Comment by PeteCausey-Freeman** [comment] 2020-04-16 14:27
Also @AnotherSimon . Thanks very much for the testing and feedback. Really useful

**Comment by ifokkema** [comment] 2020-04-16 14:34
> I will also update the docker manual specifying that the ports can be changed.
> 
> Would this be ok for both of you guys?

Sounds good for me!

**Comment by PeteCausey-Freeman** [comment] 2020-04-16 15:09
https://github.com/openvar/variantValidator/commit/c80150a821b5f54a46a8b18cf9634d5f026a3999 
closes for VV

**Comment by PeteCausey-Freeman** [comment] 2020-04-16 15:28
https://github.com/openvar/rest_variantValidator/commit/cd3a96ab510f954fedc0d35488fb944a92ec5837
Closes for the rest API

**Comment by PeteCausey-Freeman** [comment] 2020-04-16 15:55
Hi @AnotherSimon . Are you happy with the conclusions here now? If so I can close

**Comment by AnotherSimon** [comment] 2020-04-17 08:27
Well this thread has shown that the docker installation works. Still a little bit dissatisfied with not being able to just install the "old fashioned" way. Partly because I can't seem to find the documentation for making the API calls. I don't know docker well enough to know how to issue commands on the docker container and receive output back for a pipeline running on the host machine (I need batch processing, not just a local copy of the web interface, although that is a nice extra that some of my co-workers might find useful).

**Comment by PeteCausey-Freeman** [comment] 2020-04-17 14:40
Agreed to documenting some examples. Great idea. 

Also, still happy to go through the installation as well then. Might as well make the most of your input if you are willing? Really appreciate the feedback.

Most users have preferred to use docker with API but we must not assume. 

So, trouble shooting time. 

Working through the [INSTALLATION](https://github.com/openvar/variantValidator/blob/master/docs/INSTALLATION.md) - re-linking here

So, I assume that you have the pre-requisites in place and have worked through this. It looks as thought you have from the messages. How was this section? Any feedback please?

I'm not entirely sure why the config will not auto create. Did you start the MySQL server??? I assume you did. 

if you copy the config to your home directory this is the correct location. For example mine is located in home as .variantvalidator

nano .variantvalidator
```
[mysql]
host = 127.0.0.1
database = validator
user = vvadmin
password = var1ant

[seqrepo]
version = 2018-08-21
location = /Users/Shared/seqrepo_dumps/

[postgres]
host = 127.0.0.1
database = uta
version = uta_20180821
user = uta_admin
password = uta_admin

[logging]
log = True
console = DEBUG
file = ERROR

[Entrez]
email = <>
api_key = <>
```

PS: update_vdb.py suffers form the same problem. - 
# Again, i'm wondering if this is MySQL related. 
PPS: I'm working with the MySQL db dump (this required ALL PRIVILEGES to work rather than.  just SELECT,INSERT,UPDATE,DELETE as stated in the manual). 
# Noted, updating manual

I recommend building the database from the download
```bash
$ wget --output-document=validator_2019-09-18.sql.gz https://leicester.figshare.com/ndownloader/files/17714429
$ gunzip validator_2019-09-18.sql.gz
$ mysql validator < validator_2019-09-18.sql
```

**Comment by PeteCausey-Freeman** [comment] 2020-04-17 14:50
I also noticed you created the config file at 

As a workaround I have created a config file manually at "~/.variantvalidator/default.ini".

Did you alter the https://github.com/openvar/variantValidator/blob/master/VariantValidator/settings.py
to reflect these changes? 

Also can you add the content of your config file?

**Comment by PeteCausey-Freeman** [comment] 2020-04-17 14:51
I'm also happy to set up a zoom meeting to work this through and take recommendations for improving the installation documentation. Let me know what you think @AnotherSimon

**Comment by PeteCausey-Freeman** [comment] 2020-04-17 15:20
There could also be a problem with the UTA install. I have had issues building from wget http://dl.biocommons.org/uta/uta_20180821.pgd.gz. 

I am going to update the manual because I re-created and repaired this database

Download and install from 
wget https://leicester.figshare.com/ndownloader/files/17797259 -O /docker-entrypoint-initdb.d/uta_20180821.sql.gz

**Comment by PeteCausey-Freeman** [comment] 2020-04-17 15:21
Another thing to try is cd into the top variantValidator directory and run

```bash
$ pytest
```

This will let us know if anything is incorrectly configured.

You may need to pip install pytest into your vvenv

**Comment by PeteCausey-Freeman** [comment] 2020-04-17 16:10
I also have a jupyter notebook demonstrating how to use the API. I could expand it to show how to use all the endpoints. Thoughts?

**Comment by AnotherSimon** [comment] 2020-04-18 10:31
Ok, lots of things to respond to. In no particular order:

- MySQL runnning just peachy (was already in use on the system)
- The instructions at the start of the Manual.md file state that "... the edited configuration will be **placed in** the users home directory `(~/.variantvalidator)`, this location ...". I misunderstood this to mean that `settings.py` would place a copy of the config file in a hidden folder at `~/.variantvalidator`. Now I understand that this is actually the name of the config file.
- Still not sure why `settings.py` is failing though
- Running `pytest` completed mostly successfully after putting my config file in the right place with the right name (see point 1). pretty chunky testing at > 10 minutes (is there a way to skip tests that passed in the previous run?). One exception raised early on: 
```Exception ignored in: <function UTA_postgresql.__del__ at 0x7efd7cb16e60>
Traceback (most recent call last):
  File "/home/sdenil/software/anaconda3/lib/python3.7/site-packages/vvhgvs/dataproviders/uta.py", line 477, in __del__
    self.close()
  File "/home/sdenil/software/anaconda3/lib/python3.7/site-packages/vvhgvs/dataproviders/uta.py", line 481, in close
    self._pool.closeall()
AttributeError: 'UTA_postgresql' object has no attribute '_pool'`
As for actual errors:
```
==================================== ERRORS ====================================
______________ ERROR at setup of TestValidator.test_assembly_grch ______________

cls = <class 'test_core.TestValidator'>

    @classmethod
    def setUpClass(cls):
>       cls.vv = VariantValidator.Validator()

tests/test_core.py:13: 
...
dsn = 'host=localhost user=anonymous password=anonymous application_name=pytest/1.2.5.vv1 dbname=55432'
connection_factory = None, cursor_factory = None
kwargs = {'application_name': 'pytest/1.2.5.vv1', 'database': '55432', 'host': 'localhost', 'password': 'anonymous', ...}
kwasync = {}
```
My local copy of UTA runs through the docker container (recommend install option) but I had to map it to a different port becasue the default port (5432) was already in use by the system-wide install of PostGres (old version). I think something is going wrong with the way I tried to specify this in the config file:
```
[postgres]
host = localhost:55432
database = uta
version = uta_20180821
```
- Might be a bit premature for a video conference, don't think I have that much to add. The instructions were pretty clear already with the exception of the things we've cleared out here.
- Jupyter is a nice way to present code, test cases, explanation ... alongside each other but in essence it adds a dependency to be able to access your documentation. I assume most people would have access to it but you never know. Will you host the notebooks so people can just use it through their browser or will they need to self-install? (admin rights may or may not always be available)

**Comment by PeteCausey-Freeman** [comment] 2020-04-21 08:56
Actually, this is really useful information which I can use to update the manual, especially around requirements for binding additional ports for databases. 

I think I may know what the issue is. I am not entirely sure that the UTA docker has uta_20180821. It is an older version. Also, the UTA version of uta_20180821 is unreliable, so I had to re-build it. 

Have you still got the UTA version you built when installing rest_variantValidator in docker? If so, try binding to this rather than the biocommons UTA container and see if it works. To me the error message is similar to what I have seen in the past if the UTA connection fails. I am going to add an issue to provide a better warning in this instance.

Still not sure about the configure.py error. I will raise an issue and investigate. May I ask what OS you are running please?

Really appreciate all the feedback @AnotherSimon .

**Comment by PeteCausey-Freeman** [comment] 2020-04-21 09:03
Forgot to address the Jupyter.

I deliver training materials for online degrees using Jupyter. My plan is to setup rest VV to install all dependancies into the virtual env then the notebook can just be run locally with all admin rights. Will effectively be the users own copy of the user-manual which they can use and expand. Its a very effective teaching strategy which is why I'm keen to use it.

**Comment by AnotherSimon** [comment] 2020-04-22 09:01
OK, changing to the UTA version that came bundled with the REST version worked beautifully. variant_validator.py works and it resolved most pytest issues (save 12). I included the first 3 below for your reference. They all seem to be related to the values in the config file not being equal to the default (capitalised) values. This may be due to me messing around in `configuration/default.ini `. I think this concludes the open issues in this particular thread?
```
sdenil@testsrv:~/software/variantValidator$ pytest
========================================================================================== test session starts ==========================================================================================
platform linux -- Python 3.7.4, pytest-5.2.1, py-1.8.0, pluggy-0.13.0
rootdir: /home/sdenil/software/variantValidator
plugins: remotedata-0.3.2, openfiles-0.4.0, doctestplus-0.4.0, arraydiff-0.3
collected 518 items                                                                                                                                                                                     

tests/test_aa_db_update.py .ss                                                                                                                                                                    [  0%]
tests/test_configuration.py sFsFs.sFFF..                                                                                                                                                          [  2%]
tests/test_core.py .............F..............................                                                                                                                                   [ 11%]
tests/test_inputs.py .............FF.FFFF........................................................................................................................................................ [ 44%]
.......................................................................................................................................................................                           [ 76%]
tests/test_utils.py ...............................................                                                                                                                               [ 85%]
tests/test_valoutput.py ...................                                                                                                                                                       [ 89%]
tests/test_variant.py ......................................................                                                                                                                      [100%]

=============================================================================================== FAILURES ================================================================================================
________________________________________________________________________________ TestConfigSetUp.test_changed_mysql_msg _________________________________________________________________________________

self = <test_configuration.TestConfigSetUp testMethod=test_changed_mysql_msg>

    def test_changed_mysql_msg(self):
        self.insert_blank()
        self.open_config()
>       self.assertEqual(self.config['mysql']['user'], 'USERNAME')
E       AssertionError: 'VarValidator' != 'USERNAME'
E       - VarValidator
E       + USERNAME

tests/test_configuration.py:84: AssertionError
----------------------------------------------------------------------------------------- Captured stdout call ------------------------------------------------------------------------------------------
Moved file
Moved file back
_______________________________________________________________________________ TestConfigSetUp.test_changed_postgres_msg _______________________________________________________________________________

self = <test_configuration.TestConfigSetUp testMethod=test_changed_postgres_msg>

    def test_changed_postgres_msg(self):
        self.insert_blank()
        self.open_config()
        self.config['mysql']['user'] = 'myusername'
        self.config['mysql']['password'] = 'mypass'
    
>       self.assertEqual(self.config['postgres']['user'], 'USERNAME')
E       AssertionError: 'anonymous' != 'USERNAME'
E       - anonymous
E       + USERNAME

tests/test_configuration.py:119: AssertionError
----------------------------------------------------------------------------------------- Captured stdout call ------------------------------------------------------------------------------------------
Moved file
Moved file back
________________________________________________________________________________ TestConfigSetUp.test_unchanged_file_msg ________________________________________________________________________________

self = <test_configuration.TestConfigSetUp testMethod=test_unchanged_file_msg>

    def test_unchanged_file_msg(self):
        self.insert_blank()
        self.assertTrue(os.path.exists(self.filename))
        output = subprocess.check_output(['python', '-c', 'import VariantValidator'])
        print(output)
>       self.assertTrue('MySQL' in output.decode())
E       AssertionError: False is not true

tests/test_configuration.py:63: AssertionError
----------------------------------------------------------------------------------------- Captured stdout call ------------------------------------------------------------------------------------------
Moved file
b''
Moved file back

**Closed** 2022-06-29 13:30 UTC
